apiVersion: v1 
kind: Service 
metadata: 
  name: auth-svc-clusterip 
  labels: 
    svc: auth-app-clusterip 
spec: 
  selector: 
    ecommerce-app: auth-service
  ports: 
    - port: 5000 
      targetPort: 5000  
      