apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  labels:
    sec: auth-sec-app
type: Opaque
stringData:   
  JWT_SECRET: ZTRmYmM5Y2FkOGFhNTRlMmMwMTlkN2ZiNjcxNTYwNjEzOWUwOWQzYWVlNDYxODA4YTRjNDRmNTM4NjdhOTY5OTEzYjc3OWJmZWE1NmMyMDA2YmU1ZWY4YjVkYmVlZjMwY2JkYzJkZjFlYTBhYWMwYzJiYjVkOWEyODQ3NGIxOWU2
  GOOGLE_CLIENT_SECRET: R09DU1BYLTRDNDNhQZnNhWV9kS2Y1OWpESlVwWFRlVXMxX3Q=
  MONGO_URI: mongodb://admin:admin123@mongo-auth:27017/authdb?authSource=admin
