apiVersion: v1
kind: Service
metadata:
  name: mongo-auth
  namespace: microservice-app
  labels:
    app: mongo-auth
spec:
  ports:
    - port: 27017
      name: mongo
  clusterIP: None 
  selector:
    app: mongo-auth
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-auth
  namespace: microservice-app
spec:
  serviceName: "mongo-auth" 
  replicas: 3
  selector:
    matchLabels:
      app: mongo-auth
  template:
    metadata:
      labels:
        app: mongo-auth
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin123"
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
        namespace: microservice-app
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
